import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Archive, ArrowLeft, Camera, Clapperboard, Download, Film, HardDrive, Image as ImageIcon, Pencil, Plus, Search, Settings, Trash2, Upload, Users, X } from 'lucide-react';
import type { FilmRecord, CharacterRecord, SequenceRecord } from './lib/db';
import { deleteCharacter, deleteFilm, deleteSequence, listCharacters, listFilms, listSequences, saveCharacter, saveFilm, saveSequence } from './lib/projects';
import { clearAllLocalData, downloadBackup, restoreBackup } from './lib/backup';
import { getStorageEstimate, requestPersistentStorage, listPhotos } from './lib/photos';
import ContinuityWorkspace from './ContinuityWorkspace';

type Section = 'Accueil' | 'Films' | 'Personnages' | 'Séquences' | 'Continuité' | 'Sauvegarde' | 'Paramètres';
type Action = 'camera' | 'images' | undefined;
type Props = { section: Section; query: string; onDataChanged: () => void; continuityAction?: Action; onActionHandled: () => void; onNavigate: (section: Section, action?: Action) => void };
type Editor = { kind: 'film' | 'character' | 'sequence'; id?: string } | null;
type FilmBrowser = { filmId: string; characterId?: string } | null;

export default function ProjectWorkspace({ section, query, onDataChanged, continuityAction, onActionHandled, onNavigate }: Props) {
  const [films, setFilms] = useState<FilmRecord[]>([]);
  const [characters, setCharacters] = useState<CharacterRecord[]>([]);
  const [sequences, setSequences] = useState<SequenceRecord[]>([]);
  const [editor, setEditor] = useState<Editor>(null);
  const [browser, setBrowser] = useState<FilmBrowser>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  const refresh = async () => {
    const [f, c, s] = await Promise.all([listFilms(), listCharacters(), listSequences()]);
    setFilms(f); setCharacters(c); setSequences(s);
  };
  useEffect(() => { void refresh().catch(() => setError('Impossible de lire la base locale.')); }, [section]);
  useEffect(() => { if (section !== 'Films') setBrowser(null); }, [section]);

  const normalizedQuery = query.trim().toLocaleLowerCase('fr');
  const visibleFilms = useMemo(() => films.filter(f => `${f.title} ${f.description ?? ''}`.toLocaleLowerCase('fr').includes(normalizedQuery)), [films, normalizedQuery]);
  const visibleCharacters = useMemo(() => characters.filter(c => `${c.name} ${c.actorName ?? ''} ${films.find(f => f.id === c.filmId)?.title ?? ''}`.toLocaleLowerCase('fr').includes(normalizedQuery)), [characters, films, normalizedQuery]);
  const visibleSequences = useMemo(() => sequences.filter(s => `${s.name} ${s.sequenceNumber ?? ''} ${films.find(f => f.id === s.filmId)?.title ?? ''} ${characters.find(c => c.id === s.characterId)?.name ?? ''}`.toLocaleLowerCase('fr').includes(normalizedQuery)), [sequences, films, characters, normalizedQuery]);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); setNotice(''); setBusy(true); const data = new FormData(event.currentTarget);
    try {
      if (editor?.kind === 'film') await saveFilm({ id: editor.id, title: String(data.get('title') ?? ''), description: String(data.get('description') ?? '') });
      if (editor?.kind === 'character') await saveCharacter({ id: editor.id, filmId: String(data.get('filmId') ?? ''), name: String(data.get('name') ?? ''), actorName: String(data.get('actorName') ?? ''), notes: String(data.get('notes') ?? '') });
      if (editor?.kind === 'sequence') await saveSequence({ id: editor.id, characterId: String(data.get('characterId') ?? ''), name: String(data.get('name') ?? ''), sequenceNumber: String(data.get('sequenceNumber') ?? ''), description: String(data.get('description') ?? '') });
      setEditor(null); setNotice('Enregistré sur cet appareil.'); await refresh(); onDataChanged();
    } catch (e) { setError(e instanceof Error ? e.message : 'Une erreur est survenue.'); } finally { setBusy(false); }
  }

  async function remove(kind: 'film' | 'character' | 'sequence', id: string, label: string) {
    if (!window.confirm(`Supprimer « ${label} » ? Les éléments et photos qui en dépendent seront également supprimés.`)) return;
    try { if (kind === 'film') await deleteFilm(id); if (kind === 'character') await deleteCharacter(id); if (kind === 'sequence') await deleteSequence(id); setBrowser(current => current?.filmId === id ? null : current); await refresh(); onDataChanged(); setNotice('Élément supprimé.'); setError(''); } catch { setError('La suppression a échoué.'); }
  }

  if (section === 'Accueil') return <HomeDashboard films={films} characters={characters} sequences={sequences} onNavigate={onNavigate} />;
  if (section === 'Continuité') return <ContinuityWorkspace query={query} onDataChanged={onDataChanged} initialAction={continuityAction} onActionHandled={onActionHandled} />;
  if (section === 'Sauvegarde') return <BackupWorkspace onDataChanged={onDataChanged} />;
  if (section === 'Paramètres') return <SettingsWorkspace onDataChanged={onDataChanged} />;

  const editorTitle = editor?.kind === 'film' ? (editor.id ? 'Modifier le film' : 'Nouveau film') : editor?.kind === 'character' ? (editor.id ? 'Modifier le personnage' : 'Nouveau personnage') : editor?.kind === 'sequence' ? (editor.id ? 'Modifier la séquence' : 'Nouvelle séquence') : '';
  const film = editor?.kind === 'film' ? films.find(f => f.id === editor.id) : undefined;
  const character = editor?.kind === 'character' ? characters.find(c => c.id === editor.id) : undefined;
  const sequence = editor?.kind === 'sequence' ? sequences.find(s => s.id === editor.id) : undefined;
  const canCreate = section === 'Films' || (section === 'Personnages' && films.length > 0) || (section === 'Séquences' && characters.length > 0);
  const createLabel = section === 'Films' ? 'Nouveau film' : section === 'Personnages' ? 'Nouveau personnage' : 'Nouvelle séquence';
  const selectedFilm = browser ? films.find(item => item.id === browser.filmId) : undefined;
  const selectedCharacter = browser?.characterId ? characters.find(item => item.id === browser.characterId) : undefined;
  const browserCharacters = selectedFilm ? characters.filter(item => item.filmId === selectedFilm.id && `${item.name} ${item.actorName ?? ''}`.toLocaleLowerCase('fr').includes(normalizedQuery)) : [];
  const browserSequences = selectedCharacter ? sequences.filter(item => item.characterId === selectedCharacter.id && `${item.name} ${item.sequenceNumber ?? ''}`.toLocaleLowerCase('fr').includes(normalizedQuery)) : [];

  return <div className="workspace-stack">
    <div className="workspace-toolbar"><div><div className="eyebrow">GESTION DES PROJETS</div><p>{section === 'Films' ? (browser ? (selectedCharacter ? `Séquences de ${selectedCharacter.name}` : `Personnages de ${selectedFilm?.title ?? 'ce film'}`) : `${films.length} film(s) enregistré(s)`) : section === 'Personnages' ? `${characters.length} personnage(s) enregistré(s)` : `${sequences.length} séquence(s) enregistrée(s)`}</p></div><div className="toolbar-actions">{section === 'Films' && browser && <button type="button" className="outline-button compact-button" onClick={() => setBrowser(browser.characterId ? { filmId: browser.filmId } : null)}><ArrowLeft size={15}/>Retour</button>}{canCreate && <button type="button" className="primary-button" onClick={() => { setError(''); setEditor({ kind: section === 'Films' ? 'film' : section === 'Personnages' ? 'character' : 'sequence' }); }}><Plus size={17}/>{createLabel}</button>}</div></div>
    {notice && <div className="workspace-notice">{notice}</div>}{error && <div className="form-error">{error}</div>}
    {section === 'Films' && !browser && <div className="record-grid">{visibleFilms.map(item => <article className="record-card record-card-clickable" key={item.id} onClick={() => setBrowser({ filmId: item.id })} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') setBrowser({ filmId: item.id }); }} role="button" tabIndex={0}><div className="record-icon"><Clapperboard size={20}/></div><div className="record-main"><h3>{item.title}</h3><p>{item.description || 'Aucune description pour le moment.'}</p><small>{characters.filter(c => c.filmId === item.id).length} personnage(s) · {sequences.filter(s => s.filmId === item.id).length} séquence(s)</small></div><div className="record-actions"><button type="button" className="icon-button" title="Modifier" onClick={e => { e.stopPropagation(); setEditor({kind:'film',id:item.id}); }}><Pencil size={15}/></button><button type="button" className="icon-button danger-button" title="Supprimer" onClick={e => { e.stopPropagation(); void remove('film',item.id,item.title); }}><Trash2 size={15}/></button></div></article>)}{visibleFilms.length === 0 && <Empty title={normalizedQuery ? 'Aucun résultat' : 'Votre premier film vous attend'} body={normalizedQuery ? 'Essayez un autre terme de recherche.' : 'Créez un film pour commencer à organiser les personnages, les séquences et les photos de continuité.'}/>}</div>}
    {section === 'Films' && browser && !selectedCharacter && <div className="record-grid">{browserCharacters.map(item => <article className="record-card record-card-clickable" key={item.id} onClick={() => setBrowser({ filmId: browser.filmId, characterId: item.id })} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') setBrowser({ filmId: browser.filmId, characterId: item.id }); }} role="button" tabIndex={0}><div className="record-icon"><Users size={20}/></div><div className="record-main"><h3>{item.name}</h3><p>{item.actorName ? `Interprété par ${item.actorName}` : 'Acteur non renseigné'}</p><small>{selectedFilm?.title} · {sequences.filter(s => s.characterId === item.id).length} séquence(s)</small>{item.notes && <p className="record-notes">{item.notes}</p>}</div><div className="record-actions"><button type="button" className="icon-button" title="Modifier" onClick={e => { e.stopPropagation(); setEditor({kind:'character',id:item.id}); }}><Pencil size={15}/></button><button type="button" className="icon-button danger-button" title="Supprimer" onClick={e => { e.stopPropagation(); void remove('character',item.id,item.name); }}><Trash2 size={15}/></button></div></article>)}{browserCharacters.length === 0 && <Empty title="Aucun personnage" body="Ajoutez un personnage à ce film pour continuer vers ses séquences."/>}</div>}
    {section === 'Films' && browser && selectedCharacter && <div className="record-grid">{browserSequences.map(item => <article className="record-card" key={item.id}><div className="record-icon"><Film size={20}/></div><div className="record-main"><h3>{item.sequenceNumber ? `${item.sequenceNumber} — ` : ''}{item.name}</h3><p>{item.description || 'Aucune note pour cette séquence.'}</p><small>{selectedFilm?.title} · {selectedCharacter.name}</small></div><div className="record-actions"><button type="button" className="icon-button" title="Modifier" onClick={() => setEditor({kind:'sequence',id:item.id})}><Pencil size={15}/></button><button type="button" className="icon-button danger-button" title="Supprimer" onClick={() => void remove('sequence',item.id,item.name)}><Trash2 size={15}/></button></div></article>)}{browserSequences.length === 0 && <Empty title="Aucune séquence" body="Ajoutez une séquence à ce personnage pour continuer vers les photos de continuité."/>}</div>}
    {section === 'Personnages' && <div className="record-grid">{visibleCharacters.map(item => <article className="record-card" key={item.id}><div className="record-icon"><Users size={20}/></div><div className="record-main"><h3>{item.name}</h3><p>{item.actorName ? `Interprété par ${item.actorName}` : 'Acteur non renseigné'}</p><small>{films.find(f => f.id === item.filmId)?.title ?? 'Film inconnu'} · {sequences.filter(s => s.characterId === item.id).length} séquence(s)</small>{item.notes && <p className="record-notes">{item.notes}</p>}</div><div className="record-actions"><button type="button" className="icon-button" title="Modifier" onClick={() => setEditor({kind:'character',id:item.id})}><Pencil size={15}/></button><button type="button" className="icon-button danger-button" title="Supprimer" onClick={() => void remove('character',item.id,item.name)}><Trash2 size={15}/></button></div></article>)}{visibleCharacters.length === 0 && <Empty title={films.length ? 'Aucun personnage pour le moment' : 'Créez d’abord un film'} body={films.length ? 'Ajoutez une fiche personnage et associez-la à un film.' : 'Un personnage doit appartenir à un film.'}/>}</div>}
    {section === 'Séquences' && <div className="record-grid">{visibleSequences.map(item => <article className="record-card" key={item.id}><div className="record-icon"><Film size={20}/></div><div className="record-main"><h3>{item.sequenceNumber ? `${item.sequenceNumber} — ` : ''}{item.name}</h3><p>{item.description || 'Aucune note pour cette séquence.'}</p><small>{films.find(f => f.id === item.filmId)?.title} · {characters.find(c => c.id === item.characterId)?.name}</small></div><div className="record-actions"><button type="button" className="icon-button" title="Modifier" onClick={() => setEditor({kind:'sequence',id:item.id})}><Pencil size={15}/></button><button type="button" className="icon-button danger-button" title="Supprimer" onClick={() => void remove('sequence',item.id,item.name)}><Trash2 size={15}/></button></div></article>)}{visibleSequences.length === 0 && <Empty title={characters.length ? 'Aucune séquence pour le moment' : 'Ajoutez un personnage'} body={characters.length ? 'Créez une séquence et associez-la à un personnage.' : 'Les séquences sont classées dans le dossier de chaque personnage.'}/>}</div>}
    {editor && <EditorModal editor={editor} title={editorTitle} film={film} character={character} sequence={sequence} films={films} characters={characters} busy={busy} onClose={() => setEditor(null)} onSubmit={submit}/>} 
  </div>;
}

function HomeDashboard({ films, characters, sequences, onNavigate }: { films: FilmRecord[]; characters: CharacterRecord[]; sequences: SequenceRecord[]; onNavigate: Props['onNavigate'] }) {
  const [photosCount, setPhotosCount] = useState(0); const [recentPhotos, setRecentPhotos] = useState(0);
  useEffect(() => { void listPhotos().then(p => { setPhotosCount(p.length); setRecentPhotos(p.filter(x => Date.now() - new Date(x.capturedAt).getTime() < 7 * 86400000).length); }); }, []);
  const recentFilms = films.slice(0, 3);
  return <div className="home-stack">
    <section className="welcome-panel"><div className="welcome-copy"><div className="eyebrow">TABLEAU DE BORD</div><h2>Votre espace de continuité, prêt pour le plateau.</h2><p>Centralisez les films, personnages, séquences et références coiffure &amp; maquillage dans un espace local, rapide et utilisable hors ligne.</p><div className="quick-actions"><button type="button" className="quick-action" onClick={() => onNavigate('Films')}><span className="quick-action-icon"><Clapperboard size={19}/></span><span><strong>Nouveau film</strong><small>Créer ou organiser un projet</small></span></button><button type="button" className="quick-action" onClick={() => onNavigate('Personnages')}><span className="quick-action-icon"><Users size={19}/></span><span><strong>Personnages</strong><small>Gérer les fiches et acteurs</small></span></button><button type="button" className="quick-action" onClick={() => onNavigate('Continuité','images')}><span className="quick-action-icon"><ImageIcon size={19}/></span><span><strong>Ajouter des images</strong><small>Importer des références</small></span></button><button type="button" className="quick-action" onClick={() => onNavigate('Continuité','camera')}><span className="quick-action-icon"><Camera size={19}/></span><span><strong>Ouvrir la caméra</strong><small>Prendre une référence plateau</small></span></button></div></div><div className="welcome-art"><div className="art-ring"><Clapperboard size={50}/></div><span>HAIR · MAKEUP · CONTINUITY</span></div></section>
    <section className="stats-grid"><Stat icon={<Clapperboard size={20}/>} label="Films" count={films.length} detail="projets"/><Stat icon={<Users size={20}/>} label="Personnages" count={characters.length} detail="fiches"/><Stat icon={<Film size={20}/>} label="Séquences" count={sequences.length} detail="raccords"/><Stat icon={<ImageIcon size={20}/>} label="Images" count={photosCount} detail={`${recentPhotos} cette semaine`}/></section>
    <div className="home-columns"><section className="content-card"><div className="section-title-row"><div><div className="eyebrow">PROJETS RÉCENTS</div><h2>Films</h2></div><button type="button" className="text-button" onClick={() => onNavigate('Films')}>Voir tous</button></div>{recentFilms.length ? recentFilms.map(f => <button type="button" className="recent-row" key={f.id} onClick={() => onNavigate('Films')}><span className="record-icon"><Clapperboard size={17}/></span><span><strong>{f.title}</strong><small>{characters.filter(c => c.filmId === f.id).length} personnage(s) · {sequences.filter(s => s.filmId === f.id).length} séquence(s)</small></span></button>) : <Empty title="Aucun projet" body="Créez votre premier film pour commencer."/>}</section><section className="content-card"><div className="section-title-row"><div><div className="eyebrow">ACCÈS RAPIDE</div><h2>Continuité</h2></div></div><div className="home-list"><button type="button" onClick={() => onNavigate('Continuité','images')}><ImageIcon size={18}/><span>Bibliothèque d'images</span></button><button type="button" onClick={() => onNavigate('Séquences')}><Film size={18}/><span>Gérer les séquences</span></button><button type="button" onClick={() => onNavigate('Sauvegarde')}><Archive size={18}/><span>Sauvegarder le projet</span></button><button type="button" onClick={() => onNavigate('Paramètres')}><Settings size={18}/><span>État du stockage</span></button></div></section></div>
  </div>;
}
function Stat({ icon, label, count, detail }: { icon: React.ReactNode; label: string; count: number; detail: string }) { return <div className="stat-card"><div className="stat-top"><span className="stat-icon">{icon}</span><span className="stat-label">{label}</span></div><strong className="stat-count">{count}</strong><span className="stat-detail">{detail}</span></div>; }

function BackupWorkspace({ onDataChanged }: { onDataChanged: () => void }) {
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [backupInfo, setBackupInfo] = useState('');
  async function exportData() { setBusy(true); setError(''); try { const b = await downloadBackup(); setBackupInfo(`${b.films.length} films · ${b.characters.length} personnages · ${b.sequences.length} séquences · ${b.photos.length} photos`); setNotice('Sauvegarde téléchargée avec succès.'); } catch (e) { setError(e instanceof Error ? e.message : 'Export impossible.'); } finally { setBusy(false); } }
  async function importData(file?: File) { if (!file) return; if (!window.confirm('Restaurer cette sauvegarde remplacera les données locales actuelles. Continuer ?')) return; setBusy(true); setError(''); try { const r = await restoreBackup(file); setNotice('Restauration terminée.'); setBackupInfo(`${r.films} films · ${r.characters} personnages · ${r.sequences} séquences · ${r.photos} photos`); onDataChanged(); window.setTimeout(() => window.location.reload(), 500); } catch (e) { setError(e instanceof Error ? e.message : 'Restauration impossible.'); } finally { setBusy(false); } }
  return <div className="workspace-stack"><div className="backup-hero"><div><div className="eyebrow">PROTECTION DU PROJET</div><h2>Sauvegarde complète</h2><p>Exportez les données <strong>et les photos originales</strong> dans un fichier JSON local. Vous pouvez le restaurer sur un autre navigateur compatible.</p></div><div className="backup-icon"><Archive size={34}/></div></div>{notice && <div className="workspace-notice">{notice}{backupInfo && <span> · {backupInfo}</span>}</div>}{error && <div className="form-error">{error}</div>}<div className="backup-grid"><section className="content-card"><div className="backup-card-icon"><Download size={20}/></div><h3>Exporter</h3><p>Crée une sauvegarde autonome avec films, personnages, séquences, réglages et photos.</p><button type="button" className="primary-button full-button" onClick={() => void exportData()} disabled={busy}><Download size={17}/>{busy ? 'Traitement…' : 'Télécharger la sauvegarde'}</button></section><section className="content-card"><div className="backup-card-icon"><Upload size={20}/></div><h3>Restaurer</h3><p>Importez une sauvegarde créée par Continuité Cinéma. Les données actuelles seront remplacées.</p><label className="file-button"><Upload size={17}/>Choisir une sauvegarde<input type="file" accept="application/json,.json" onChange={e => void importData(e.target.files?.[0])}/></label></section></div><div className="field-hint">Conseil : faites une sauvegarde après chaque journée de tournage. Les photos peuvent rendre le fichier volumineux.</div></div>;
}

function SettingsWorkspace({ onDataChanged }: { onDataChanged: () => void }) {
  const [storage, setStorage] = useState<{usage?:number;quota?:number}>({}); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  async function refresh() { setStorage(await getStorageEstimate()); }
  useEffect(() => { void refresh(); }, []);
  const formatBytes = (n?: number) => n === undefined ? '—' : n < 1024*1024 ? `${(n/1024).toFixed(0)} Ko` : `${(n/1024/1024).toFixed(1)} Mo`;
  async function persist() { const result = await requestPersistentStorage(); setNotice(result ? 'Le navigateur a accordé le stockage persistant.' : 'Le navigateur n’a pas accordé le stockage persistant. Faites des sauvegardes régulières.'); }
  async function reset() { if (!window.confirm('Supprimer TOUTES les données locales, y compris les photos ? Cette action est irréversible sans sauvegarde.')) return; try { await clearAllLocalData(); onDataChanged(); setNotice('Toutes les données locales ont été supprimées.'); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Suppression impossible.'); } }
  const percent = storage.usage && storage.quota ? Math.min(100, storage.usage / storage.quota * 100) : 0;
  return <div className="workspace-stack"><section className="content-card settings-card"><div className="section-title-row"><div><div className="eyebrow">APPAREIL</div><h2>Stockage local</h2></div><HardDrive size={22}/></div><div className="storage-meter"><div style={{width:`${percent}%`}}/></div><div className="storage-values"><span>Utilisé : <strong>{formatBytes(storage.usage)}</strong></span><span>Quota estimé : <strong>{formatBytes(storage.quota)}</strong></span></div><div className="settings-actions"><button type="button" className="outline-button" onClick={() => void persist()}>Conserver le stockage</button><button type="button" className="outline-button" onClick={() => { void refresh(); }}>Actualiser</button></div><p className="field-hint">Les données sont locales au navigateur et à cet appareil. Le mode hors ligne ne remplace pas une sauvegarde.</p></section>{notice && <div className="workspace-notice">{notice}</div>}{error && <div className="form-error">{error}</div>}<section className="content-card danger-card"><div className="eyebrow">ZONE DE DANGER</div><h3>Réinitialiser les données locales</h3><p>Supprime films, personnages, séquences, photos et réglages de cet appareil. Exportez d’abord une sauvegarde si vous souhaitez pouvoir revenir en arrière.</p><button type="button" className="danger-solid-button" onClick={() => void reset()}><Trash2 size={17}/>Supprimer toutes les données</button></section></div>;
}

function EditorModal({ editor, title, film, character, sequence, films, characters, busy, onClose, onSubmit }: { editor: NonNullable<Editor>; title: string; film?: FilmRecord; character?: CharacterRecord; sequence?: SequenceRecord; films: FilmRecord[]; characters: CharacterRecord[]; busy: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="editor-modal" role="dialog" aria-modal="true"><div className="editor-heading"><div><div className="eyebrow">CONTINUITÉ · DOSSIER</div><h2>{title}</h2></div><button type="button" className="icon-button" aria-label="Fermer" onClick={onClose}><X size={18}/></button></div><form className="project-form" onSubmit={onSubmit}>
    {editor.kind === 'film' && <><label>Titre du film *<input name="title" defaultValue={film?.title ?? ''} required autoFocus maxLength={120} placeholder="Ex. Le dernier été"/></label><label>Description / production<textarea name="description" defaultValue={film?.description ?? ''} rows={3} maxLength={2000} placeholder="Informations utiles sur le projet…"/></label></>}
    {editor.kind === 'character' && <><label>Film associé *<select name="filmId" defaultValue={character?.filmId ?? films[0]?.id ?? ''} required>{films.map(f => <option value={f.id} key={f.id}>{f.title}</option>)}</select></label><label>Nom du personnage *<input name="name" defaultValue={character?.name ?? ''} required autoFocus maxLength={120} placeholder="Ex. Claire"/></label><label>Nom de l’acteur / actrice<input name="actorName" defaultValue={character?.actorName ?? ''} maxLength={120} placeholder="Nom de l’interprète"/></label><label>Informations complémentaires<textarea name="notes" defaultValue={character?.notes ?? ''} rows={3} maxLength={3000} placeholder="Description physique, repères de continuité…"/></label></>}
    {editor.kind === 'sequence' && <><label>Personnage associé *<select name="characterId" defaultValue={sequence?.characterId ?? characters[0]?.id ?? ''} required>{characters.map(c => <option value={c.id} key={c.id}>{c.name} — {films.find(f => f.id === c.filmId)?.title}</option>)}</select></label><label>Nom de la séquence *<input name="name" defaultValue={sequence?.name ?? ''} required autoFocus maxLength={120} placeholder="Ex. Intérieur — Chambre"/></label><label>Numéro de séquence<input name="sequenceNumber" defaultValue={sequence?.sequenceNumber ?? ''} maxLength={40} placeholder="Ex. 12A"/></label><label>Description / repères<textarea name="description" defaultValue={sequence?.description ?? ''} rows={3} maxLength={3000} placeholder="État de la coiffure, maquillage, accessoires…"/></label></>}
    <div className="editor-actions"><button type="button" className="outline-button" onClick={onClose}>Annuler</button><button type="submit" className="primary-button" disabled={busy}>{busy ? 'Enregistrement…' : 'Enregistrer'}</button></div>
  </form></section></div>;
}
function Empty({ title, body }: { title: string; body: string }) { return <div className="workspace-empty"><div className="placeholder-icon"><Search size={25}/></div><h2>{title}</h2><p>{body}</p></div>; }
